import { NextResponse } from "next/server";
import fs from "node:fs";
import path from "node:path";
import { ensureInit } from "@/lib/init";
import db from "@/lib/db";
import { getRunDir } from "@/lib/run-paths";
import { getDriveClient, downloadFile } from "@/lib/services/gdrive";
import { resumeRun, canResumeRun } from "@/lib/pipeline";
import { log } from "@/lib/logger";

/**
 * Recover a run by downloading its previously-uploaded clips from Drive back
 * to local disk, then triggering Resume.
 *
 * Use cases:
 *   - Run's local assets were cleaned up but Drive still has the clips (e.g.
 *     after a crash that triggered partial cleanup).
 *   - Re-render an old finished video with new music / overlay / QR without
 *     paying for clip regeneration.
 *   - Re-assemble after settings changed (transitions, tail silence, etc.).
 *
 * Bypasses Grok generation entirely for any scene whose clip is present in the
 * Drive Clips Library folder of this run. Costs ZERO 69labs credits (only
 * Drive download bandwidth).
 *
 * Scenes missing from BOTH local disk AND Drive will still be regenerated by
 * the Resume that fires after the download finishes.
 */
export async function POST(_: Request, ctx: { params: Promise<{ id: string }> }) {
  ensureInit();
  const { id } = await ctx.params;

  if (!canResumeRun(id)) {
    return NextResponse.json(
      {
        error:
          "This run can't be recovered — no saved scene plan (scenes.json) on disk. Run was probably aborted before scene-splitting finished.",
      },
      { status: 400 }
    );
  }

  const row = db
    .prepare("SELECT drive_clips_folder_id FROM runs WHERE id = ?")
    .get(id) as { drive_clips_folder_id: string | null } | undefined;

  if (!row?.drive_clips_folder_id) {
    return NextResponse.json(
      {
        error:
          "This run has no Drive Clips Library folder linked. It was never successfully uploaded to Drive, so there's nothing to recover from. Use Resume instead.",
      },
      { status: 400 }
    );
  }

  const drive = getDriveClient();
  if (!drive) {
    return NextResponse.json(
      { error: "Google Drive is not connected. Connect it in Settings first." },
      { status: 400 }
    );
  }

  // Fire-and-forget — work happens async and the user watches via SSE logs.
  (async () => {
    const runDir = getRunDir(id);
    const animDir = path.join(runDir, "animations");
    fs.mkdirSync(animDir, { recursive: true });

    log(id, "info", `Recover from Drive started — pulling clips back to disk`, {
      stage: "pipeline",
    });

    try {
      // List all mp4 files in the run's Drive clips folder (paginate just in case)
      const allFiles: { id: string; name: string }[] = [];
      let pageToken: string | undefined;
      do {
        const res = await drive.files.list({
          q: `'${row.drive_clips_folder_id}' in parents and trashed=false and name contains '.mp4'`,
          fields: "files(id, name), nextPageToken",
          pageSize: 1000,
          pageToken,
        });
        for (const f of res.data.files ?? []) {
          if (f.id && f.name) allFiles.push({ id: f.id, name: f.name });
        }
        pageToken = res.data.nextPageToken ?? undefined;
      } while (pageToken);

      log(
        id,
        "info",
        `Found ${allFiles.length} clip${allFiles.length === 1 ? "" : "s"} in Drive folder — downloading the missing ones to disk`,
        { stage: "pipeline" }
      );

      let downloaded = 0;
      let skipped = 0;
      let failed = 0;
      for (const f of allFiles) {
        // Only consider files that look like scene_NNN.mp4
        if (!/^scene_\d+\.mp4$/i.test(f.name)) continue;

        const localPath = path.join(animDir, f.name);
        if (fs.existsSync(localPath) && fs.statSync(localPath).size > 0) {
          skipped++;
          continue;
        }

        try {
          await downloadFile(f.id, localPath);
          downloaded++;
          if (downloaded % 25 === 0) {
            log(id, "debug", `Recover: ${downloaded} clips downloaded so far...`, {
              stage: "pipeline",
            });
          }
        } catch (e) {
          failed++;
          const msg = e instanceof Error ? e.message : String(e);
          log(id, "warn", `Recover: failed to download ${f.name}: ${msg.slice(0, 120)}`, {
            stage: "pipeline",
          });
        }
      }

      log(
        id,
        "success",
        `Recover finished: ${downloaded} downloaded, ${skipped} already on disk, ${failed} failed. Triggering Resume to re-assemble.`,
        { stage: "pipeline" }
      );

      // Now trigger Resume — every scene that has a clip on disk will be skipped
      // by the pipeline's "already on disk" check, so only truly-missing scenes
      // (no Drive backup AND no local clip) will hit Grok.
      await resumeRun(id);
    } catch (e) {
      const msg = e instanceof Error ? e.message : String(e);
      log(id, "error", `Recover from Drive failed: ${msg.slice(0, 250)}`, {
        stage: "pipeline",
      });
    }
  })().catch((e) => {
    // eslint-disable-next-line no-console
    console.error("recover-from-drive crash", e);
  });

  return NextResponse.json({ ok: true });
}
